# netlify.toml
[build]
  publish = "."
  functions = "netlify/functions"

# Optional: add headers so the site can be embedded in Wix via iFrame
# You can restrict frame-ancestors to your exact wix domain after testing.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://*.wixsite.com https://*.editorx.io https://*.wix.com https://*.wixapps.net https://*.wixstatic.com 'self'"
