# netlify.toml
[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://acreinsights.com https://www.acreinsights.com https://*.wixsite.com https://*.editorx.io https://*.wix.com https://*.wixapps.net https://*.wixstatic.com 'self'"
